[tool.black]
line-length = 120
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | __pycache__
  | data
  | outputs
  | logs
  | notebooks
  | \.github
)/
'''